### ISSUE TITLE
After converting password does not working

### ISSUE THREAD

**Issue by Leen29** [sakicnet/SMF2Kunena#2]
hello after I've converted to SMF Kunena according to the explanation.
Hello

After i've migrated SMF forum to kunena i have user login problems. All the users are migrated, so that went well, but none of them are able to log in with their SMF login details
Could you please help me to solve this problem?
f.y.i. i use sh404sef and jfusion

i hope to hear from you soon,
Kind regards

**Comment by sakicnet** [comment]
Have you installed and enabled the SMF authentication plugin? (Step 6 in https://github.com/sakicnet/SMF2Kunena#usage).

**Comment by Leen29** [comment]
oops I forgot to do
I have now done so we start testing again,
you'll hear from me if it works

**Comment by Leen29** [comment]
It all seems to work now
Thank you
with greeting Leen
